<a href="https://colab.research.google.com/github/25pa1a4590-hue/python_lab/blob/main/Nasscom_lab(1).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [ ]:
#1d array
import numpy as np
arr = np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [ ]:
#2d array
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3d array
c=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
#to check dimensions
a=np.array(52)
b=np.array((1,2,3,4,5))
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[7,8,9,],[10,11,12]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
#accessing elements in array
a=np.array([[1,2,3],[4,5,6]])
print("5th element in 2ndrow:",a[1,2])

5th element in 2ndrow: 6


In [ ]:
#in 3d
b=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)
print(b[1,1,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
12


In [ ]:
#accessing back
a=np.array([[1,2,3,9,10],[4,5,6,7,8]])
print(a)
print(a[-1,-4])

[[ 1  2  3  9 10]
 [ 4  5  6  7  8]]
5


In [ ]:
#checking the data type in array
a=np.array([1,2,3])
print(arr.dtype)

int64


In [ ]:
import numpy as np
a=np.array([1,2,3,4.4])
print(a.dtype)

float64


In [ ]:
#copy or view
a=np.array([1,2,3,4,5])
x=a.copy()
a[0]=42
print(a)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [ ]:
a=np.array([1,2,3,4,5])
x=a.view()
a[0]=42
print(a)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


In [ ]:
#shape of array
a=np.array([[1,2,3],[5,6,7]])
print(a.shape)


(2, 3)


In [ ]:
a=np.array([1,2,3,4,5],ndmin=5)
print(a)
print(a.shape)

[[[[[1 2 3 4 5]]]]]
(1, 1, 1, 1, 5)


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7,8,9,10,11,12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
#linear algebra
A = np.array([[1,2],[3,4]])
B = np.array([5,6])
X = np.linalg.solve(A,B)
print(X)

[-4.   4.5]


In [12]:
#built in functions
import numpy as np
a0 = np.zeros((3, 3))
a1  = np.ones((2, 2))
a2  = np.arange(0, 10, 2)
print(a0)
print(a1)
print(a2)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]]
[0 2 4 6 8]
